# Loops and Patterns

## while loop

In [1]:
i=1 ### initializing

while i<=5: # condition
    print('Data Science')
    i=i+1 # increment

Data Science
Data Science
Data Science
Data Science
Data Science


In [2]:
i=1 ### initializing

while i<=5: # condition
    print('Data Science:', i)
    i=i+1 # increment

Data Science: 1
Data Science: 2
Data Science: 3
Data Science: 4
Data Science: 5


In [3]:
i=5 ### initializing

while i>=1: # condition
    print('Data Science:', i)
    i=i-1 # decrement

Data Science: 5
Data Science: 4
Data Science: 3
Data Science: 2
Data Science: 1


### nested while loop

In [4]:
i=1
while i<=3:
    print('Data Science:',i)
    j=1
    while j<=2:
        print('Technology:',j)
        j=j+1
    i=i+1
    print()

Data Science: 1
Technology: 1
Technology: 2

Data Science: 2
Technology: 1
Technology: 2

Data Science: 3
Technology: 1
Technology: 2



#### end attribute in print() to avoid to print next statement in new line

In [6]:
i=1
while i<=3:
    print('Data Science:',i, end=" ")# when we menstion end, then new line will not create
    j=1
    while j<=2:
        print('Technology:',j, end=" ")
        j=j+1
    i=i+1
    print()

Data Science: 1 Technology: 1 Technology: 2 
Data Science: 2 Technology: 1 Technology: 2 
Data Science: 3 Technology: 1 Technology: 2 


In [7]:
i=1
while i<=2:
    j=0
    while j<=2:
        print(i*j, end=" ")
        j +=1
    print()
    i +=1

0 1 2 
0 2 4 


In [8]:
i=1
while i<=4:
    j=0
    while j<=3:
        print(i*j, end=" ")
        j +=1
    print()
    i +=1

0 1 2 3 
0 2 4 6 
0 3 6 9 
0 4 8 12 


### FOR LOOP
#### normally while loop, it works with iteration or some certain conditions but for loop it will work with sequence(list, string, int)

In [9]:
name='vasanth'

for j in name:
    print(j)

v
a
s
a
n
t
h


In [10]:
name1=[1,2,3.5,'okula']

for i in name1:
    print(i)

1
2
3.5
okula


In [11]:
for i in [2,3,7.8,'hi']:
    print(i)

2
3
7.8
hi


In [12]:
range(5)

range(0, 5)

In [13]:
for i in range(5):
    print(i)

0
1
2
3
4


In [14]:
for i in range(2,5):
    print(i)

2
3
4


In [15]:
for i in range(1,10,3):
    print(i)

1
4
7


In [16]:
for i in range(1,10,5):
    print(i)

1
6


#### print the value which is divisible by 5

In [17]:
for i in range(1,51):
    if i%5==0:
        print(i,end=" ")

5 10 15 20 25 30 35 40 45 50 

#### print the value which is divisible by 3

In [18]:
for i in range(1,31):
    if i%3==0:
        print(i,end=" ")

3 6 9 12 15 18 21 24 27 30 

#### print the values which are not divisible by 3

In [19]:
for i in range(1,31):
    if i%3!=0:
        print(i,end=" ")

1 2 4 5 7 8 10 11 13 14 16 17 19 20 22 23 25 26 28 29 

#### print the values which are not divisible by 5

In [20]:
for i in range(1,51):
    if i%5!=0:
        print(i,end=" ")

1 2 3 4 6 7 8 9 11 12 13 14 16 17 18 19 21 22 23 24 26 27 28 29 31 32 33 34 36 37 38 39 41 42 43 44 46 47 48 49 

In [22]:
for i in range(1,11):
    print(i, end=" ")

1 2 3 4 5 6 7 8 9 10 

#### break ---> break the loop
  

In [23]:
for i in range(1,11):
    if(i==5):
        break
    print(i, end="  ")

1  2  3  4  

In [24]:
for i in range(1,11):
    if(i==6):
        break
    print(i, end="  ")

1  2  3  4  5  

#### continue ----- skip the current part and continue with next iteration in loop

##### in continue, loop wont be terminate and exclude the assign number and gives you entire output

In [25]:
for i in range(1,11):
    if(i==6):
        continue
    print(i, end="  ")

1  2  3  4  5  7  8  9  10  

#### pass

In [27]:
for i in range(1,10):

SyntaxError: incomplete input (4054113036.py, line 1)

In [28]:
for i in range(1,10):
    pass # to avoid systax error we can use pass

In [29]:
for i in range(1,11):
    if i==6:
        continue
    print('Hello:',i, end="   ")

Hello: 1   Hello: 2   Hello: 3   Hello: 4   Hello: 5   Hello: 7   Hello: 8   Hello: 9   Hello: 10   

### Print the number which is not divisible by 3 or 5 from 1 to 50 

In [30]:
for i in range(1,51):
    if i%3==0 or i%5==0:
        continue
    print(i, end="  ")

1  2  4  7  8  11  13  14  16  17  19  22  23  26  28  29  31  32  34  37  38  41  43  44  46  47  49  

#### patterns in python

In [32]:
for i in range(1,5):
    print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [33]:
for i in range(4):
    print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [34]:
for i in range(4):
    for j in range(4):
        print('#', end=' ')
    print()

# # # # 
# # # # 
# # # # 
# # # # 


### 1. Right angle Triangle pattern

In [35]:
for i in range(1,6):
    print('*'*i)

*
**
***
****
*****


### 2. Inverted Right angle Triangle Pattern

In [36]:
for i in range(5,0,-1):
    print('*'*i)

*****
****
***
**
*


### 3. Pyramid Pattern

In [38]:
rows=10
for i in range(1, rows+1):
    print(' '*(rows-i)+'* '*i)

         * 
        * * 
       * * * 
      * * * * 
     * * * * * 
    * * * * * * 
   * * * * * * * 
  * * * * * * * * 
 * * * * * * * * * 
* * * * * * * * * * 


### 4. Inverted Pyramid Pattern

In [39]:
rows=10
for i in range(rows, 0, -1):
    print(' '*(rows-i)+'* '*i)

* * * * * * * * * * 
 * * * * * * * * * 
  * * * * * * * * 
   * * * * * * * 
    * * * * * * 
     * * * * * 
      * * * * 
       * * * 
        * * 
         * 


### 5.Diamond Pattern

In [40]:
rows=10
for i in range(1, rows+1):
    print(' '*(rows-i)+'* '*i)
for i in range(rows-1, 0,-1):
    print(' '*(rows-i)+'* '*i)

         * 
        * * 
       * * * 
      * * * * 
     * * * * * 
    * * * * * * 
   * * * * * * * 
  * * * * * * * * 
 * * * * * * * * * 
* * * * * * * * * * 
 * * * * * * * * * 
  * * * * * * * * 
   * * * * * * * 
    * * * * * * 
     * * * * * 
      * * * * 
       * * * 
        * * 
         * 


### 6. Hallow Square Pattern

In [43]:
for i in range(5):
    for j in range(5):
        if i==0 or i==4 or j==0 or j==4:
            print('*', end='')
        else:
            print(' ',end='')
    print()

*****
*   *
*   *
*   *
*****


### 7. Full Square Pattern

In [46]:
for i in range(5):
    print('* '*5)

* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 


### 8. Right Angle Trianle (Number Pattern)

In [55]:
for i in range(1,6):
    for j in range(1,6):
        if i>=j:
            print(j, end='')
    print()

1
12
123
1234
12345


### 9. Inverted Right Angle Trianle (Number Pattern)

In [58]:
count=5
for i in range(1,6):
    for j in range(1,6):
        if count>=j:
            print(j, end='')
    print()
    count= count-1

12345
1234
123
12
1


### 10.  Floyd's Triangle

In [60]:
count=1
for i in range(1,6):
    for j in range(1,6):
        if i>=j:
            print(count, end=' ')
            count+=1
    print()

1 
2 3 
4 5 6 
7 8 9 10 
11 12 13 14 15 


### 11. Hallow Right angle

In [64]:
for i in range(1,6):
    for j in range(1, i+1):
        if i==5 or j==1 or j==i:
            print('*', end=' ')
        else:
            print(' ',end=' ')
    print()

* 
* * 
*   * 
*     * 
* * * * * 


### for else

#### If loop will finish without interruption(means with out executing break), so the else block will execute

##### write a program to find a number which is divisible by 5 in given set of numbers

In [65]:
nums = [7,14,18,21,23,27] #hear there is no number which is divisible by 5 we got output as blank

for num in nums:
    if num % 5 == 0:
        print(num)  
        break
else:
        print('Number Not Found')

Number Not Found


In [66]:
nums = [10,14,18,21,20,27] #hear there is no number which is divisible by 5 we got output as blank

for num in nums:
    if num % 5 == 0:
        print(num)  
        break
else:
        print('Not Found')

10


### check given number is prime or not

In [69]:
num=int(input('Enter a number to check whether its prime or not::'))
for i in range(2, num):
    if num%i==0:
        print("Given Number is not a prime number")
        break
else:
    print("Prime Number")

Enter a number to check whether its prime or not:: 9


Given Number is not a prime number


### Array in Python

In [71]:
from array import *
arr=array('i',[])

n=int(input('Enter the length of an array'))

for i in range(n):
    x=int(input('Enter the next value'))
    arr.append(x)
print(arr)

Enter the length of an array 6
Enter the next value 2
Enter the next value 4
Enter the next value 7
Enter the next value 5
Enter the next value 9
Enter the next value 8


array('i', [2, 4, 7, 5, 9, 8])


### Way of creating array using numpy

In [72]:
from numpy import *
arr = array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [73]:
print(arr.dtype)

int32


In [74]:
arr = array([1,2,3,4,5.9])
print(arr)

[1.  2.  3.  4.  5.9]


In [75]:
print(arr.dtype)

float64


In [76]:
arr2 = array([1,2,3,4,5.9],float)
arr2

array([1. , 2. , 3. , 4. , 5.9])

In [77]:
arr3 = array([1,2,3,4,5.6],int)
arr3

array([1, 2, 3, 4, 5])

In [78]:
import numpy as np

In [79]:
arr4 = np.linspace(0, 16, 10) # break the code between 10 spaces between 0 to 16 but why decimal becuase we break into parts thats why it is floats
arr4

array([ 0.        ,  1.77777778,  3.55555556,  5.33333333,  7.11111111,
        8.88888889, 10.66666667, 12.44444444, 14.22222222, 16.        ])

In [81]:
arr5 = np.arange(0,10,2) # arange - as range
arr5

array([0, 2, 4, 6, 8])

In [82]:
arr6 = np.zeros(5)
arr6

array([0., 0., 0., 0., 0.])

In [83]:
arr7 = np.ones(5)
arr7

array([1., 1., 1., 1., 1.])